# Generated by Django 4.2.3 on 2023-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android1_icon', models.CharField(max_length=300)),
                ('android1_title', models.CharField(max_length=300)),
                ('android1_des', models.TextField(max_length=300)),
                ('android2_icon', models.CharField(max_length=300)),
                ('android2_title', models.CharField(max_length=300)),
                ('android2_des', models.TextField(max_length=300)),
                ('android3_icon', models.CharField(max_length=300)),
                ('android3_title', models.CharField(max_length=300)),
                ('android3_des', models.TextField(max_length=300)),
            ],
        ),
    ]
