# Generated by Django 4.2.3 on 2023-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web1_icon', models.CharField(max_length=300)),
                ('web1_title', models.CharField(max_length=300)),
                ('web1_des', models.TextField(max_length=300)),
                ('web2_icon', models.CharField(max_length=300)),
                ('web2_title', models.CharField(max_length=300)),
                ('web2_des', models.TextField(max_length=300)),
                ('web3_icon', models.CharField(max_length=300)),
                ('web3_title', models.CharField(max_length=300)),
                ('web3_des', models.TextField(max_length=300)),
            ],
        ),
    ]
