# Generated by Django 4.2.3 on 2023-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_team',
            field=models.TextField(max_length=300),
        ),
    ]
