# Generated by Django 4.2.3 on 2023-09-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIUX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiux1_icon', models.CharField(max_length=300)),
                ('uiux1_title', models.CharField(max_length=300)),
                ('uiux1_des', models.TextField(max_length=300)),
                ('uiux2_icon', models.CharField(max_length=300)),
                ('uiux2_title', models.CharField(max_length=300)),
                ('uiux2_des', models.TextField(max_length=300)),
                ('uiux3_icon', models.CharField(max_length=300)),
                ('uiux3_title', models.CharField(max_length=300)),
                ('uiux3_des', models.TextField(max_length=300)),
            ],
        ),
    ]
